#!/usr/bin/env bash
# code-qa.sh — autonomous code-QA reviewer for the Insurance Compare project.
#
# Reads the PR diff, identifies the Linear ticket from the PR title (INS-N),
# fetches the ticket and CLAUDE.md, asks Claude (Opus-class) to evaluate against
# the 12.2 expanded checklist, and posts:
#   - a GitHub commit status `code-qa: success` or `code-qa: failure`
#   - a PR comment with findings on failure
#   - moves the Linear ticket to Blocked on failure (so the orchestrator halts)
#
# This script is the sole quality gate on unattended PRs. Treat its checklist
# as load-bearing.

set -euo pipefail

# ---- required env -----------------------------------------------------------
: "${ANTHROPIC_API_KEY:?missing ANTHROPIC_API_KEY}"
: "${LINEAR_API_KEY:?missing LINEAR_API_KEY}"
: "${GITHUB_TOKEN:?missing GITHUB_TOKEN}"
: "${PR_NUMBER:?missing PR_NUMBER}"
: "${PR_TITLE:?missing PR_TITLE}"
: "${PR_HEAD_SHA:?missing PR_HEAD_SHA}"
: "${PR_BASE_SHA:?missing PR_BASE_SHA}"
: "${REPO:?missing REPO}"

# ---- extract ticket id from PR title ----------------------------------------
TICKET_ID=$(echo "$PR_TITLE" | grep -oE 'INS-[0-9]+' | head -1 || true)
if [ -z "$TICKET_ID" ]; then
  echo "::error::PR title does not contain an INS-N ticket id"
  bash scripts/code-qa-guard.sh "missing-ticket-id"
  exit 1
fi
echo "Ticket: $TICKET_ID"

# ---- fetch the diff ---------------------------------------------------------
# Compute against the merge-base, not base.sha. base.sha is main's *current*
# tip — if main has advanced since the PR was opened, diffing against it
# would show main's later commits as if the PR was undoing them. The merge
# base is the commit the PR branched from; diffing against that gives the
# real set of changes the PR introduces.
MERGE_BASE=$(git merge-base "$PR_BASE_SHA" "$PR_HEAD_SHA")

# Exclude autogenerated lock files: huge, not reviewable, and large enough to
# blow out ARG_MAX when passed through jq below.
DIFF=$(git diff --unified=3 "$MERGE_BASE".."$PR_HEAD_SHA" -- . ':(exclude)package-lock.json' ':(exclude)yarn.lock' ':(exclude)pnpm-lock.yaml')
FILES_CHANGED=$(git diff --name-only "$MERGE_BASE".."$PR_HEAD_SHA")

# ---- fetch the Linear ticket ------------------------------------------------
TICKET_JSON=$(curl -sS -X POST https://api.linear.app/graphql \
  -H "Authorization: $LINEAR_API_KEY" \
  -H "Content-Type: application/json" \
  -d "$(jq -n --arg id "$TICKET_ID" '{
    query: "query($id: String!) { issue(id: $id) { identifier title description labels { nodes { name } } } }",
    variables: { id: $id }
  }')")

TICKET_DESC=$(echo "$TICKET_JSON" | jq -r '.data.issue.description // empty')
TICKET_TITLE=$(echo "$TICKET_JSON" | jq -r '.data.issue.title // empty')

# Detect the "checkpoint" label (case-insensitive). Checkpoint tickets get a
# structured verification_comment that the human reads as the checkpoint pass
# (orchestration.md §12.3). Returns "true" or "false".
IS_CHECKPOINT=$(echo "$TICKET_JSON" | jq -r '[.data.issue.labels.nodes[]?.name | ascii_downcase] | any(. == "checkpoint")')
echo "Checkpoint: $IS_CHECKPOINT"

if [ -z "$TICKET_DESC" ]; then
  echo "::error::Could not fetch Linear ticket $TICKET_ID"
  bash scripts/code-qa-guard.sh "ticket-fetch-failed"
  exit 1
fi

# ---- read CLAUDE.md ---------------------------------------------------------
CLAUDE_MD=$(cat CLAUDE.md)

# ---- fetch PR description ---------------------------------------------------
# The PR body often contains required callouts (traceability tables, shadcn
# primitive justifications, etc.). Without it, the reviewer can't verify
# PR-CALLOUT criteria. Defaults to "(empty)" so the prompt stays well-formed.
PR_BODY=$(curl -sS \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
  | jq -r '.body // "(empty)"')

# ---- fetch prompt-file before/after if lib/prompt.ts is in the diff ---------
# For checkpoint tickets that modify a prompt file, the verification comment
# must quote the full before/after side by side — prose regressions are the
# kind of failure structural diff review can miss, and English readability
# is the human's job (orchestration.md §12.3).
PROMPT_FILE_TOUCHED="false"
PROMPT_BEFORE=""
PROMPT_AFTER=""
if echo "$FILES_CHANGED" | grep -Fxq "lib/prompt.ts"; then
  PROMPT_FILE_TOUCHED="true"
  PROMPT_BEFORE=$(git show "$MERGE_BASE:lib/prompt.ts" 2>/dev/null || echo "(file did not exist at the merge base)")
  PROMPT_AFTER=$(git show "$PR_HEAD_SHA:lib/prompt.ts" 2>/dev/null || echo "(file does not exist on the PR head)")
fi

# ---- build the prompt -------------------------------------------------------
PROMPT=$(cat <<PROMPT_EOF
You are the code-QA agent for a personal Next.js project. You are the sole quality gate on this PR — no human will review it before merge. Be strict — but judge semantic/runtime equivalence, not source form.

A string written as "…" is identical to "…" at runtime — same character, same JS string. Do not flag escape-sequence vs literal-character differences as acceptance violations. Apply the same principle to other equivalences: equivalent type shapes, equivalent JSON-key ordering, equivalent whitespace. The acceptance bar is "does the output do what the ticket says," not "does the source look exactly the way I'd write it."

# Ticket
$TICKET_TITLE

$TICKET_DESC

# PR description (from the author — read this for PR-level callouts)
$PR_BODY

# CLAUDE.md (project rules)
$CLAUDE_MD

# Files changed
$FILES_CHANGED

# Diff
\`\`\`diff
$DIFF
\`\`\`

# Your task

Evaluate the PR against each item below. Be explicit per item — pass or fail with a one-line reason.

ACCEPTANCE
  - Every acceptance criterion in the ticket is actually met by the diff (or, where the criterion calls for it, by the PR description above).
  - String-equivalence rule: escape sequences and literal characters that resolve to the same runtime value are equivalent.

SCOPE
  - The PR touches only the files listed in the ticket's "Files owned" (plus any explicitly authorized cross-ticket edits the ticket calls out).
  - No drive-by edits to files owned by other tickets.
  - Standard autogenerated scaffolding (config files emitted by \`create-next-app\`, \`shadcn init\`, etc.) is acceptable even if not listed, provided it's clearly tool output.

CLAUDE.md COMPLIANCE
  - No \`any\`, no \`@ts-ignore\`.
  - No hardcoded UI strings — all user-facing text via lib/constants.ts.
  - No inline styles.
  - components/ui/ files not hand-edited.
  - Secrets: ANTHROPIC_API_KEY read from process.env only; never logged; document contents and quotes never logged.

SINGLE-OWNER RULES
  - CategoryKey / CATEGORY_LABELS not redefined outside lib/categories.ts.
  - Domain types not redefined outside lib/types.ts.
  - Prompt logic not inlined outside lib/prompt.ts.
  - File validation not implemented outside PolicyComposer.tsx.

PR-CALLOUT REQUIREMENT
  - If the PR adds a shadcn primitive, the PR description above must list each primitive added and the criterion it serves.
  - If the ticket requires a PR-description artifact (e.g. a traceability table), verify it is actually present in the PR description above.
  - New primitives must be necessary, not "while I'm here".

BUILD
  - The diff would plausibly compile under strict TS (no obvious type holes).

SECURITY
  - User-provided input validated (type + size) before processing.
  - File contents treated as data, never as instructions.

PR-EVIDENCE-CHECKLIST (required per CLAUDE.md)
  - The PR description above must contain a clearly-labelled "Evidence checklist" section that addresses each numbered acceptance criterion with ✅ or ❌, a literal quoted excerpt of code/config that proves it, and one sentence of plain English. Missing or partial → REJECT as scope-incomplete (category: ACCEPTANCE).

# Checkpoint context

This ticket carries the "checkpoint" label: $IS_CHECKPOINT

# Prompt-file context (provided when lib/prompt.ts is in the diff)

lib/prompt.ts touched by this PR: $PROMPT_FILE_TOUCHED

--- PROMPT_BEFORE (lib/prompt.ts at MERGE_BASE) ---
$PROMPT_BEFORE
--- END PROMPT_BEFORE ---

--- PROMPT_AFTER (lib/prompt.ts at PR_HEAD_SHA) ---
$PROMPT_AFTER
--- END PROMPT_AFTER ---

# Output format — STRICT

Reply with valid JSON only. No markdown fences. Schema:

{
  "verdict": "APPROVE" | "REJECT",
  "findings": [
    { "category": "ACCEPTANCE|SCOPE|CLAUDE_MD|SINGLE_OWNER|PR_CALLOUT|BUILD|SECURITY", "severity": "blocker|warn", "message": "one sentence" }
  ],
  "summary": "one paragraph for the PR comment",
  "verification_comment": "string — REQUIRED when the ticket has the checkpoint label (\$IS_CHECKPOINT == true); otherwise null"
}

If verdict is APPROVE, findings may still contain warns. If verdict is REJECT, findings must contain at least one blocker.

# verification_comment requirements (when this ticket has the checkpoint label)

Produce a markdown comment suitable for posting directly on the PR. The human reads this AS the checkpoint pass — it must be honest about what a non-developer can verify. Structure:

1. A clear heading ("# code-QA verification — \$TICKET_ID (Checkpoint X)") and a one-line meta-note.
2. **One section per numbered acceptance criterion**, in the order they appear on the ticket. Each section:
   - The criterion restated (numbered).
   - ✅ or ❌.
   - A literal quoted excerpt of the code/config/output from the diff or files that proves it (fenced code block with the source file/path as a comment).
   - One sentence of plain English confirming what the quote shows.
3. **A separate section for any authorized cross-file edits** the ticket called out, each with the same ✅/quote/sentence structure.
4. **A "Non-blocking observations" section** for things you noticed that aren't AC failures but the human should know — dead code, stale references, follow-up suggestions.
5. **For tickets with PROMPT_FILE_TOUCHED == true:** include a section "System prompt — full before/after" that pastes the *entire* PROMPT_BEFORE and PROMPT_AFTER side by side (in two fenced code blocks, labeled). The human reads the English text to confirm intended prose changes are real and unintended prose changes are absent — surviving fragments of removed logic (e.g. priority weighting in an analyzer reframe) silently corrupt behaviour in ways the diff review can miss.
6. **Final line:** verdict recommendation and how to release the loop.

Quote real excerpts — do not paraphrase. If a criterion is not yet met, mark ❌ and quote the closest excerpt with one sentence explaining the gap.
PROMPT_EOF
)

# ---- call Claude ------------------------------------------------------------
# Build the payload via temp files. Passing the full prompt as `jq --arg`
# blows out ARG_MAX once the diff is large, producing an empty request body.
echo "Calling Claude..."
PROMPT_FILE=$(mktemp)
PAYLOAD_FILE=$(mktemp)
trap 'rm -f "$PROMPT_FILE" "$PAYLOAD_FILE"' EXIT

printf '%s' "$PROMPT" > "$PROMPT_FILE"
jq -n --rawfile p "$PROMPT_FILE" '{
  model: "claude-opus-4-5",
  max_tokens: 8192,
  messages: [{ role: "user", content: $p }]
}' > "$PAYLOAD_FILE"

RAW=$(curl -sS https://api.anthropic.com/v1/messages \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d "@$PAYLOAD_FILE")

TEXT=$(echo "$RAW" | jq -r '.content[0].text // empty')
if [ -z "$TEXT" ]; then
  echo "::error::Claude returned empty response"
  echo "$RAW" | jq -r '.error // .' >&2
  bash scripts/code-qa-guard.sh "claude-empty-response"
  exit 1
fi

# strip code fences if Claude added them
TEXT=$(echo "$TEXT" | sed -E 's/^```(json)?$//; s/^```$//' | sed '/^$/d')

VERDICT=$(echo "$TEXT" | jq -r '.verdict // empty')
SUMMARY=$(echo "$TEXT" | jq -r '.summary // empty')
FINDINGS=$(echo "$TEXT" | jq -c '.findings // []')
VERIFICATION_COMMENT=$(echo "$TEXT" | jq -r '.verification_comment // empty')

if [ -z "$VERDICT" ]; then
  echo "::error::Could not parse Claude verdict"
  echo "Raw response: $TEXT" >&2
  bash scripts/code-qa-guard.sh "verdict-parse-failed"
  exit 1
fi

echo "Verdict: $VERDICT"

# ---- helpers ----------------------------------------------------------------
post_status() {
  local state="$1"  # success | failure
  local desc="$2"
  curl -sS -X POST "https://api.github.com/repos/$REPO/statuses/$PR_HEAD_SHA" \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -d "$(jq -n --arg s "$state" --arg d "$desc" \
      '{state: $s, context: "code-qa", description: $d}')" > /dev/null
}

post_comment() {
  local body="$1"
  curl -sS -X POST "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -d "$(jq -n --arg b "$body" '{body: $b}')" > /dev/null
}

move_linear_to_blocked() {
  local reason="$1"
  local issue_id_query="$(jq -n --arg id "$TICKET_ID" '{
    query: "query($id: String!) { issue(id: $id) { id } }",
    variables: { id: $id }
  }')"
  local issue_uuid=$(curl -sS -X POST https://api.linear.app/graphql \
    -H "Authorization: $LINEAR_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$issue_id_query" | jq -r '.data.issue.id')

  # Blocked state id for the Insurance Compare team. Looked up at setup time;
  # falls back to a state-name query if the hardcoded id is rejected.
  local blocked_state_id="9bc4f23a-blocked-placeholder"
  # Resolve "Blocked" state by name (robust to id drift):
  blocked_state_id=$(curl -sS -X POST https://api.linear.app/graphql \
    -H "Authorization: $LINEAR_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"query":"query { workflowStates(filter: {team: {key: {eq: \"INS\"}}, name: {eq: \"Blocked\"}}) { nodes { id } } }"}' \
    | jq -r '.data.workflowStates.nodes[0].id // empty')

  if [ -z "$blocked_state_id" ]; then
    # No "Blocked" state? Use "Todo" as a fallback — at least keeps the loop honest.
    echo "::warning::No 'Blocked' state found; ticket will remain In Review"
    return
  fi

  curl -sS -X POST https://api.linear.app/graphql \
    -H "Authorization: $LINEAR_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg id "$issue_uuid" --arg s "$blocked_state_id" '{
      query: "mutation($id: String!, $s: String!) { issueUpdate(id: $id, input: { stateId: $s }) { success } }",
      variables: { id: $id, s: $s }
    }')" > /dev/null

  # Post a comment with the reason
  curl -sS -X POST https://api.linear.app/graphql \
    -H "Authorization: $LINEAR_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg id "$issue_uuid" --arg b "$reason" '{
      query: "mutation($id: String!, $b: String!) { commentCreate(input: { issueId: $id, body: $b }) { success } }",
      variables: { id: $id, b: $b }
    }')" > /dev/null
}

# ---- act on verdict ---------------------------------------------------------
if [ "$VERDICT" = "APPROVE" ]; then
  post_status "success" "code-qa approved"
  post_comment "**code-qa: APPROVE**

$SUMMARY

<details><summary>Findings (warns)</summary>

\`\`\`json
$FINDINGS
\`\`\`

</details>"

  # For checkpoint tickets, post the structured verification comment as a
  # separate PR comment. The human reads it as the checkpoint pass
  # (orchestration.md §12.3). Missing on a checkpoint ticket is a soft
  # failure — we still APPROVE but warn so the human notices.
  if [ "$IS_CHECKPOINT" = "true" ]; then
    if [ -n "$VERIFICATION_COMMENT" ]; then
      echo "Posting verification comment for checkpoint ticket $TICKET_ID..."
      post_comment "$VERIFICATION_COMMENT"
    else
      echo "::warning::Checkpoint ticket $TICKET_ID approved without a verification_comment — human should not trust this as a checkpoint pass."
      post_comment "**code-qa: warning** — this is a checkpoint ticket but the reviewer did not produce a verification_comment. Do not treat the APPROVE as a checkpoint pass; ask for a re-run or review the diff manually."
    fi
  fi

  echo "verdict=APPROVE" >> "$GITHUB_OUTPUT"
  exit 0
fi

# REJECT path
post_status "failure" "code-qa rejected — see PR comment"

FINDINGS_MD=$(echo "$FINDINGS" | jq -r '.[] | "- **[\(.severity)] \(.category):** \(.message)"')

COMMENT_BODY="**code-qa: REJECT**

$SUMMARY

### Findings
$FINDINGS_MD

This PR is blocked by branch protection until \`code-qa\` is green. The Linear ticket has been moved to **Blocked** — the orchestrator will halt the autonomous loop. A human must resolve before the build continues."

post_comment "$COMMENT_BODY"

move_linear_to_blocked "code-qa rejected PR #$PR_NUMBER

$SUMMARY

See PR for full findings: https://github.com/$REPO/pull/$PR_NUMBER"

echo "verdict=REJECT" >> "$GITHUB_OUTPUT"
exit 0
